apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: health-hazard-tracker
build:
  local:
    push: false # Prevents Skaffold from attempting to upload to Docker Hub
  artifacts:
    - image: health-hazard-tracker # Must match your Dockerfile build image name
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  helm:
    releases:
      - name: health-hazard-tracker-local
        chartPath: ./charts
        namespace: local
        createNamespace: true
        # Dynamically replaces your values.yaml fields with the newly built local image
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO}}"
          image.tag: "{{.IMAGE_TAG}}"
