spring.application.name=outbreak-tracker

spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.probes.enabled=true

fda.api.key=${FDA_API_KEY:default_or_mock_key}
