apiVersion: v1
kind: Secret
metadata:
  name: health-hazard-api-secrets
  namespace: local
type: Opaque
stringData:
  # Helm will fetch these values from your computer during deployment
  THIRD_PARTY_API_KEY: {{ .Values.apiKeys.thirdPartyKey | quote }}
