apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-hazard-tracker-deployment
  namespace: default
  labels:
    app: health-hazard-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: health-hazard-tracker
  template:
    metadata:
      labels:
        app: health-hazard-tracker
    spec:
      containers:
        - name: app_container
          image: scot04100/health-hazard-tracker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
